### ISSUE TITLE
Create Toph MICROSERVICE

### ISSUE THREAD

**Issue by Norbbs** [fjborquez/toph#1]
For unit of measurement and common things...

DATA:
https://docs.google.com/spreadsheets/d/1_EtjTbCWO3zb2Z9RPbkBIz79-kaCMIvGz3xepeCNU98/edit?gid=0#gid=0

MICROSERVICE MIRO:
https://miro.com/app/board/uXjVNTxXLPY=/

**Comment by fjborquez** [comment]
Crear tablas, poblarlas y exponer las unidades de medidas en un endpoint (solo lectura de todas las unidades)
